test_that("tomoSeq Object", {
    load("simulateData.rda")
    load("rec_results.rda")
    tomoSeqObject <- MakeTomoObjSet(testx, testy, testz, mask = mask)
    expect_identical(class(tomoSeqObject), c("tomoSeq", "R6"))
    expect_identical(tomoSeqObject$expMatOriginal[[1]], testx)
    expect_identical(tomoSeqObject$expMatOriginal[[2]], testy)
    expect_identical(tomoSeqObject$expMatOriginal[[3]], testz)
    expect_identical(tomoSeqObject$geneList, c("gene1", "gene2", "gene3", "gene4"))
    expect_identical(tomoSeqObject$mask, mask)
    expect_error(tomoSeqObject$GetReconstructedResult("gene1"))
})
